services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod$$"
      DOODBA_ENVIRONMENT: "prod"
      INITIAL_LANG: "fr_FR"
      LIST_DB: "false"
      ODOO_BUS_PUBLIC_SAMESITE_WS: 1
      PGHOST: ibatix-stack-prod-db
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      traefik.enable: "true"
      traefik.docker.network: "inverseproxy_shared"
      traefik.http.routers.ibatix-app.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.ibatix-app.entrypoints: "websecure"
      traefik.http.routers.ibatix-app.tls.certresolver: "letsencrypt"
      traefik.http.routers.ibatix-app.service: "ibatix-app"
      traefik.http.services.ibatix-app.loadbalancer.server.port: "8069"
      traefik.http.routers.ibatix-lp.rule: "Host(`${DOMAIN}`) && PathPrefix(`/longpolling`, `/websocket`)"
      traefik.http.routers.ibatix-lp.entrypoints: "websecure"
      traefik.http.routers.ibatix-lp.tls.certresolver: "letsencrypt"
      traefik.http.routers.ibatix-lp.service: "ibatix-lp"
      traefik.http.services.ibatix-lp.loadbalancer.server.port: "8072"

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      DB_HOST: ibatix-stack-prod-db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "ibatix-stack-prod-db"

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
